#!/usr/bin/env bash
#
# Build a universal (arm64 + x86_64) macOS binary with xmake and package it as
# a zip, ready to attach to a GitHub release.
#
# Usage: ./package.sh
#
set -euo pipefail
cd "$(dirname "$0")"

# Bump this to release a new version. It is injected into the binary and used
# for the package name, so it is the single source of truth.
VERSION="0.0.3"

APP="mff"
PLAT="macosx"
MODE="release"
DIST="dist"

NAME="${APP}-${VERSION}-${PLAT}-universal"
ZIP="${DIST}/${NAME}.zip"
UNIVERSAL="${DIST}/${APP}"
ARM="build/${PLAT}/arm64/${MODE}/${APP}"
INTEL="build/${PLAT}/x86_64/${MODE}/${APP}"

echo "==> ${APP} ${VERSION}: writing src/Version.swift"
cat > src/Version.swift <<EOF
// Generated by package.sh — do not edit.
// Change VERSION in package.sh to bump the version.
let kAppVersion = "${VERSION}"
EOF

echo "==> ${APP} ${VERSION}: building ${PLAT} arm64 + x86_64 (${MODE})"
for arch in arm64 x86_64; do
    echo "    [${arch}] xmake configure + build"
    xmake f -y -a "${arch}" -m "${MODE}" >/dev/null
    xmake -y -r >/dev/null
done

for f in "${ARM}" "${INTEL}"; do
    if [ ! -f "${f}" ]; then
        echo "error: missing build artifact: ${f}" >&2
        exit 1
    fi
done

mkdir -p "${DIST}"
rm -f "${UNIVERSAL}" "${ZIP}"

echo "==> lipo -create -> ${UNIVERSAL}"
lipo -create -output "${UNIVERSAL}" "${ARM}" "${INTEL}"
lipo -info "${UNIVERSAL}"

# arm64 binaries must carry at least an ad-hoc signature to run.
echo "==> ad-hoc codesign"
codesign --force --sign - "${UNIVERSAL}" 2>/dev/null || true

echo "==> zip -> ${ZIP}"
( cd "${DIST}" && zip -q -9 "${NAME}.zip" "${APP}" )
rm -f "${UNIVERSAL}"

# Leave the build configured for the host so a plain `xmake b` still works.
xmake f -y -a "$(uname -m)" -m "${MODE}" >/dev/null 2>&1 || true

echo
echo "Created ${ZIP}"
echo
echo "Upload to GitHub, e.g.:"
echo "  gh release create v${VERSION} '${ZIP}' --title v${VERSION} --generate-notes"
echo "  gh release upload v${VERSION} '${ZIP}' --clobber"
